### ISSUE TITLE
Sound gone

### ISSUE THREAD

**Issue by snakeeater98** [Ilya114/Box64Droid#122]
After updating OneUI from 6.0 to 6.1 the sound is no longer working.
I use Box64Droid only in DEX mode.

Allready tryed reinstalling Termux and TermuxX11.

**Comment by Ilya114** [comment]
Android ver? And send logs

**Comment by F1LIP3** [comment]
got the same issue on mobox for samsung galaxy s23, and was fixed by this:

Adding this here for anyone in the future. Another solution is to add this to the front of the pulse audio command. This should fix pulse audio.

File: /data/data/com.termux/files/usr/glibc/opt/scripts/start-tfm

Before:

pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1

After:

LD_PRELOAD=/system/lib64/libskcodec.so pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1


But I couldnt find this script on box64droid, maybe Ilya114 knows where it is

**Comment by snakeeater98** [comment]
how do i access/edit that file, i don't have root access

**Comment by F1LIP3** [comment]
cd .. on termux then It Will be intuitive

**Comment by snakeeater98** [comment]
that actually fixed the sound. thanks legend, case closed.
