### ISSUE TITLE
x11 doesnt work after second time

### ISSUE THREAD

**Issue by hoholee12** [Ilya114/Box64Droid#19]
**Describe the bug**

installing and running for the first time, everything works.
but it doesnt work after first time.

**To reproduce**

kill termux
relaunch termux
start-box
same procedure
x11 says not connected.
i tried killing running x11 processes and tried again but no dice.

- Try '...' 

**Screenshots**

If possible, make and add screenshots in spoiler to help explain your problem.

<details>

</details>

**Smartphone (please complete the following information):**

 - Device: tab s7+
 - OS: android 13
 - Termux version 0.118

**Comment by Ilya114** [comment]
It working for me. Try reinstall Termux

**Comment by hoholee12** [comment]
> It working for me. Try reinstall Termux

that is the point. it works when i delete 5gb worth of termux and reinstall everything from the beginning.
i don't want to have to reinstall the whole termux and proot EVERYTIME i want to use this.

**Comment by Ilya114** [comment]
Maybe device problem or ROM, idk. It working for me all times

**Comment by Luihart** [comment]
Maybe restart the Phone works for him too. Did you try?
@Ilya114 Suggestion: Maybe you can build in, in next Update to delete a Container or create a new Container? Because Sometimes Install or Change Wine Version Breaks box86/64 and we have to reinstall Termux from scratch everytime to solve this. Maybe with delete Container and create new Container will save that process of reinstalling complete Termux. Is this a possible Thing? Psvita Guru and me reinstalled it several Times, Just because of testing several settings. Otherwise keep Up good working! Best Update so far! And thx!

**Comment by Ilya114** [comment]
> Suggestion: Maybe you can build in, in next Update to delete a Container or create a new Container?

Will be hard to release, so not now

**Comment by hoholee12** [comment]
> Maybe restart the Phone works for him too. Did you try?
> @Ilya114 Suggestion: Maybe you can build in, in next Update to delete a Container or create a new Container? Because Sometimes Install or Change Wine Version Breaks box86/64 and we have to reinstall Termux from scratch everytime to solve this. Maybe with delete Container and create new Container will save that process of reinstalling complete Termux. Is this a possible Thing? Psvita Guru and me reinstalled it several Times, Just because of testing several settings. Otherwise keep Up good working! Best Update so far! And thx!

i rebooted and it didnt work. the only thing that works is to reinstall termux and everything else from scratch.

**Comment by Sirox228** [comment]
for me, rebooting the phone gives you another one run

**Comment by Luihart** [comment]
> I have this problem only when I try to change the default wine version to a different one.
> 
> Default wine = works everytime I open. Change wine version = only works once.

Yes happened to me too. Before changing Wine i recommend to reboot Phone First. That make Sure that No old process were active and to avoid mounting problems

**Comment by seven768** [comment]
This bug is somehow related to TFM.exe, it breaks after the first run and therefore the script does not work properly on the second run.  
Open the "start" file in "Z:/opt/"(or path: "/data/data/com.termux/files/home/ubuntu/opt/", if you have root) with some text editor  and delete two lines like this: "/opt/TFM".  After that, the startup script should work, but now you won't have a file manager, but you can use Wine explorer(Start-run-explorer) or Winefile for example. Thanks to Ilya for this trick

**Comment by Luihart** [comment]
Thx for the Idea. I now have method to Stop box64 correctly, since in chroot it doesnt Work properly, i Just Close all Windows and Software in active Container. This stops box64 automatically. Maybe this helps Others too

**Comment by ashraf456** [comment]
Yes  I Also Face this Problem , 
I have a Solution 
After exit from termux app
Force stop Termux And Run Again 
It's Work for me .
Termux-x11 is Running in Background 
If it's Running You can't Stop it By exit command
You Need To Force stop Termux app to kill Termux-x11

**Comment by fxmbsw7** [comment]
i ve met many founs that block so much u cant connect .. esp since its an andro unsupported part .. its unix cmds and shell base

**Comment by kryptous** [comment]
I posted this on the other Issue and not sure if it should be posted again but here is what works for me.(thanks to Ilya for the script where the commands came from)

In termux type:
`start-box-root`

type option 1 for box64

type desired resolution e.g 800x600

press `control + c`

Enter command to stop desktop in background:
`box64 wineserver -k`

Enter command to start desktop in termux-x11:
`taskset -c 4-7 box64 wine explorer /desktop=shell,$res /opt/TFM`

**Comment by seven768** [comment]
> I posted this on the other Issue and not sure if it should be posted again but here is what works for me. I had the same problem. (thanks to Ilya for the script where the commands came from)
Thank you, it works👍

**Comment by Ilya114** [comment]
Well, kill box64 now should work normall

**Comment by Ilya114** [comment]
Closing due a inactivity
